/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as ComoJogarRouteImport } from './routes/como-jogar'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GanhadoresRouteImport } from './routes/ganhadores'
import { Route as HomeRouteImport } from './routes/home'
import { Route as JogoResponsavelRouteImport } from './routes/jogo-responsavel'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as RaspadinhasRouteImport } from './routes/raspadinhas'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AuthenticatedCarteiraRouteImport } from './routes/_authenticated/carteira'
import { Route as AuthenticatedCuponsRouteImport } from './routes/_authenticated/cupons'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedIndicacaoRouteImport } from './routes/_authenticated/indicacao'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedTransacoesRouteImport } from './routes/_authenticated/transacoes'
import { Route as RaspadinhaSlugRouteImport } from './routes/raspadinha.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminBannersRouteImport } from './routes/_authenticated/admin/banners'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin/configuracoes'
import { Route as AuthenticatedAdminCuponsRouteImport } from './routes/_authenticated/admin/cupons'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminFinanceiroRouteImport } from './routes/_authenticated/admin/financeiro'
import { Route as AuthenticatedAdminGanhadoresRouteImport } from './routes/_authenticated/admin/ganhadores'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated/admin/logs'
import { Route as AuthenticatedAdminPremiosRouteImport } from './routes/_authenticated/admin/premios'
import { Route as AuthenticatedAdminRelatoriosRouteImport } from './routes/_authenticated/admin/relatorios'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedCarteiraAdicionarRouteImport } from './routes/_authenticated/carteira/adicionar'
import { Route as AuthenticatedCarteiraSaqueRouteImport } from './routes/_authenticated/carteira/saque'
import { Route as AuthenticatedAdminRaspadinhasIndexRouteImport } from './routes/_authenticated/admin/raspadinhas/index'
import { Route as AuthenticatedAdminRaspadinhasIdRouteImport } from './routes/_authenticated/admin/raspadinhas/$id'
import { Route as AuthenticatedAdminRaspadinhasNovoRouteImport } from './routes/_authenticated/admin/raspadinhas/novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoJogarRoute = ComoJogarRouteImport.update({
  id: '/como-jogar',
  path: '/como-jogar',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GanhadoresRoute = GanhadoresRouteImport.update({
  id: '/ganhadores',
  path: '/ganhadores',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const JogoResponsavelRoute = JogoResponsavelRouteImport.update({
  id: '/jogo-responsavel',
  path: '/jogo-responsavel',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const RaspadinhasRoute = RaspadinhasRouteImport.update({
  id: '/raspadinhas',
  path: '/raspadinhas',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCarteiraRoute = AuthenticatedCarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCuponsRoute = AuthenticatedCuponsRouteImport.update({
  id: '/cupons',
  path: '/cupons',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIndicacaoRoute = AuthenticatedIndicacaoRouteImport.update({
  id: '/indicacao',
  path: '/indicacao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransacoesRoute = AuthenticatedTransacoesRouteImport.update({
  id: '/transacoes',
  path: '/transacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const RaspadinhaSlugRoute = RaspadinhaSlugRouteImport.update({
  id: '/raspadinha/$slug',
  path: '/raspadinha/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminBannersRoute =
  AuthenticatedAdminBannersRouteImport.update({
    id: '/admin/banners',
    path: '/admin/banners',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/admin/configuracoes',
    path: '/admin/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCuponsRoute =
  AuthenticatedAdminCuponsRouteImport.update({
    id: '/admin/cupons',
    path: '/admin/cupons',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFinanceiroRoute =
  AuthenticatedAdminFinanceiroRouteImport.update({
    id: '/admin/financeiro',
    path: '/admin/financeiro',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminGanhadoresRoute =
  AuthenticatedAdminGanhadoresRouteImport.update({
    id: '/admin/ganhadores',
    path: '/admin/ganhadores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminPremiosRoute =
  AuthenticatedAdminPremiosRouteImport.update({
    id: '/admin/premios',
    path: '/admin/premios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRelatoriosRoute =
  AuthenticatedAdminRelatoriosRouteImport.update({
    id: '/admin/relatorios',
    path: '/admin/relatorios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCarteiraAdicionarRoute =
  AuthenticatedCarteiraAdicionarRouteImport.update({
    id: '/adicionar',
    path: '/adicionar',
    getParentRoute: () => AuthenticatedCarteiraRoute,
  } as any)
const AuthenticatedCarteiraSaqueRoute =
  AuthenticatedCarteiraSaqueRouteImport.update({
    id: '/saque',
    path: '/saque',
    getParentRoute: () => AuthenticatedCarteiraRoute,
  } as any)
const AuthenticatedAdminRaspadinhasIndexRoute =
  AuthenticatedAdminRaspadinhasIndexRouteImport.update({
    id: '/admin/raspadinhas/',
    path: '/admin/raspadinhas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRaspadinhasIdRoute =
  AuthenticatedAdminRaspadinhasIdRouteImport.update({
    id: '/admin/raspadinhas/$id',
    path: '/admin/raspadinhas/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRaspadinhasNovoRoute =
  AuthenticatedAdminRaspadinhasNovoRouteImport.update({
    id: '/admin/raspadinhas/novo',
    path: '/admin/raspadinhas/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/como-jogar': typeof ComoJogarRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/faq': typeof FaqRoute
  '/ganhadores': typeof GanhadoresRoute
  '/home': typeof HomeRoute
  '/jogo-responsavel': typeof JogoResponsavelRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/raspadinhas': typeof RaspadinhasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/carteira': typeof AuthenticatedCarteiraRouteWithChildren
  '/cupons': typeof AuthenticatedCuponsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/indicacao': typeof AuthenticatedIndicacaoRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/transacoes': typeof AuthenticatedTransacoesRoute
  '/raspadinha/$slug': typeof RaspadinhaSlugRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/ganhadores': typeof AuthenticatedAdminGanhadoresRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/premios': typeof AuthenticatedAdminPremiosRoute
  '/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/carteira/adicionar': typeof AuthenticatedCarteiraAdicionarRoute
  '/carteira/saque': typeof AuthenticatedCarteiraSaqueRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/raspadinhas/$id': typeof AuthenticatedAdminRaspadinhasIdRoute
  '/admin/raspadinhas/novo': typeof AuthenticatedAdminRaspadinhasNovoRoute
  '/admin/raspadinhas/': typeof AuthenticatedAdminRaspadinhasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/como-jogar': typeof ComoJogarRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/faq': typeof FaqRoute
  '/ganhadores': typeof GanhadoresRoute
  '/home': typeof HomeRoute
  '/jogo-responsavel': typeof JogoResponsavelRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/raspadinhas': typeof RaspadinhasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/carteira': typeof AuthenticatedCarteiraRouteWithChildren
  '/cupons': typeof AuthenticatedCuponsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/indicacao': typeof AuthenticatedIndicacaoRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/transacoes': typeof AuthenticatedTransacoesRoute
  '/raspadinha/$slug': typeof RaspadinhaSlugRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/ganhadores': typeof AuthenticatedAdminGanhadoresRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/premios': typeof AuthenticatedAdminPremiosRoute
  '/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/carteira/adicionar': typeof AuthenticatedCarteiraAdicionarRoute
  '/carteira/saque': typeof AuthenticatedCarteiraSaqueRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/raspadinhas/$id': typeof AuthenticatedAdminRaspadinhasIdRoute
  '/admin/raspadinhas/novo': typeof AuthenticatedAdminRaspadinhasNovoRoute
  '/admin/raspadinhas': typeof AuthenticatedAdminRaspadinhasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/como-jogar': typeof ComoJogarRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/faq': typeof FaqRoute
  '/ganhadores': typeof GanhadoresRoute
  '/home': typeof HomeRoute
  '/jogo-responsavel': typeof JogoResponsavelRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/raspadinhas': typeof RaspadinhasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/_authenticated/carteira': typeof AuthenticatedCarteiraRouteWithChildren
  '/_authenticated/cupons': typeof AuthenticatedCuponsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/indicacao': typeof AuthenticatedIndicacaoRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/transacoes': typeof AuthenticatedTransacoesRoute
  '/raspadinha/$slug': typeof RaspadinhaSlugRoute
  '/_authenticated/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/_authenticated/admin/ganhadores': typeof AuthenticatedAdminGanhadoresRoute
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/admin/premios': typeof AuthenticatedAdminPremiosRoute
  '/_authenticated/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/carteira/adicionar': typeof AuthenticatedCarteiraAdicionarRoute
  '/_authenticated/carteira/saque': typeof AuthenticatedCarteiraSaqueRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/raspadinhas/$id': typeof AuthenticatedAdminRaspadinhasIdRoute
  '/_authenticated/admin/raspadinhas/novo': typeof AuthenticatedAdminRaspadinhasNovoRoute
  '/_authenticated/admin/raspadinhas/': typeof AuthenticatedAdminRaspadinhasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/como-funciona'
    | '/como-jogar'
    | '/esqueci-senha'
    | '/faq'
    | '/ganhadores'
    | '/home'
    | '/jogo-responsavel'
    | '/login'
    | '/privacidade'
    | '/raspadinhas'
    | '/reset-password'
    | '/suporte'
    | '/termos'
    | '/carteira'
    | '/cupons'
    | '/dashboard'
    | '/indicacao'
    | '/perfil'
    | '/transacoes'
    | '/raspadinha/$slug'
    | '/admin/banners'
    | '/admin/configuracoes'
    | '/admin/cupons'
    | '/admin/dashboard'
    | '/admin/financeiro'
    | '/admin/ganhadores'
    | '/admin/logs'
    | '/admin/premios'
    | '/admin/relatorios'
    | '/admin/usuarios'
    | '/carteira/adicionar'
    | '/carteira/saque'
    | '/admin/'
    | '/admin/raspadinhas/$id'
    | '/admin/raspadinhas/novo'
    | '/admin/raspadinhas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/como-funciona'
    | '/como-jogar'
    | '/esqueci-senha'
    | '/faq'
    | '/ganhadores'
    | '/home'
    | '/jogo-responsavel'
    | '/login'
    | '/privacidade'
    | '/raspadinhas'
    | '/reset-password'
    | '/suporte'
    | '/termos'
    | '/carteira'
    | '/cupons'
    | '/dashboard'
    | '/indicacao'
    | '/perfil'
    | '/transacoes'
    | '/raspadinha/$slug'
    | '/admin/banners'
    | '/admin/configuracoes'
    | '/admin/cupons'
    | '/admin/dashboard'
    | '/admin/financeiro'
    | '/admin/ganhadores'
    | '/admin/logs'
    | '/admin/premios'
    | '/admin/relatorios'
    | '/admin/usuarios'
    | '/carteira/adicionar'
    | '/carteira/saque'
    | '/admin'
    | '/admin/raspadinhas/$id'
    | '/admin/raspadinhas/novo'
    | '/admin/raspadinhas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cadastro'
    | '/como-funciona'
    | '/como-jogar'
    | '/esqueci-senha'
    | '/faq'
    | '/ganhadores'
    | '/home'
    | '/jogo-responsavel'
    | '/login'
    | '/privacidade'
    | '/raspadinhas'
    | '/reset-password'
    | '/suporte'
    | '/termos'
    | '/_authenticated/carteira'
    | '/_authenticated/cupons'
    | '/_authenticated/dashboard'
    | '/_authenticated/indicacao'
    | '/_authenticated/perfil'
    | '/_authenticated/transacoes'
    | '/raspadinha/$slug'
    | '/_authenticated/admin/banners'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/cupons'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/financeiro'
    | '/_authenticated/admin/ganhadores'
    | '/_authenticated/admin/logs'
    | '/_authenticated/admin/premios'
    | '/_authenticated/admin/relatorios'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/carteira/adicionar'
    | '/_authenticated/carteira/saque'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/raspadinhas/$id'
    | '/_authenticated/admin/raspadinhas/novo'
    | '/_authenticated/admin/raspadinhas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ComoJogarRoute: typeof ComoJogarRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  FaqRoute: typeof FaqRoute
  GanhadoresRoute: typeof GanhadoresRoute
  HomeRoute: typeof HomeRoute
  JogoResponsavelRoute: typeof JogoResponsavelRoute
  LoginRoute: typeof LoginRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RaspadinhasRoute: typeof RaspadinhasRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SuporteRoute: typeof SuporteRoute
  TermosRoute: typeof TermosRoute
  RaspadinhaSlugRoute: typeof RaspadinhaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-jogar': {
      id: '/como-jogar'
      path: '/como-jogar'
      fullPath: '/como-jogar'
      preLoaderRoute: typeof ComoJogarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ganhadores': {
      id: '/ganhadores'
      path: '/ganhadores'
      fullPath: '/ganhadores'
      preLoaderRoute: typeof GanhadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogo-responsavel': {
      id: '/jogo-responsavel'
      path: '/jogo-responsavel'
      fullPath: '/jogo-responsavel'
      preLoaderRoute: typeof JogoResponsavelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raspadinhas': {
      id: '/raspadinhas'
      path: '/raspadinhas'
      fullPath: '/raspadinhas'
      preLoaderRoute: typeof RaspadinhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/carteira': {
      id: '/_authenticated/carteira'
      path: '/carteira'
      fullPath: '/carteira'
      preLoaderRoute: typeof AuthenticatedCarteiraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cupons': {
      id: '/_authenticated/cupons'
      path: '/cupons'
      fullPath: '/cupons'
      preLoaderRoute: typeof AuthenticatedCuponsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/indicacao': {
      id: '/_authenticated/indicacao'
      path: '/indicacao'
      fullPath: '/indicacao'
      preLoaderRoute: typeof AuthenticatedIndicacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transacoes': {
      id: '/_authenticated/transacoes'
      path: '/transacoes'
      fullPath: '/transacoes'
      preLoaderRoute: typeof AuthenticatedTransacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/raspadinha/$slug': {
      id: '/raspadinha/$slug'
      path: '/raspadinha/$slug'
      fullPath: '/raspadinha/$slug'
      preLoaderRoute: typeof RaspadinhaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/banners': {
      id: '/_authenticated/admin/banners'
      path: '/admin/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AuthenticatedAdminBannersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/cupons': {
      id: '/_authenticated/admin/cupons'
      path: '/admin/cupons'
      fullPath: '/admin/cupons'
      preLoaderRoute: typeof AuthenticatedAdminCuponsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/financeiro': {
      id: '/_authenticated/admin/financeiro'
      path: '/admin/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/ganhadores': {
      id: '/_authenticated/admin/ganhadores'
      path: '/admin/ganhadores'
      fullPath: '/admin/ganhadores'
      preLoaderRoute: typeof AuthenticatedAdminGanhadoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/premios': {
      id: '/_authenticated/admin/premios'
      path: '/admin/premios'
      fullPath: '/admin/premios'
      preLoaderRoute: typeof AuthenticatedAdminPremiosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/relatorios': {
      id: '/_authenticated/admin/relatorios'
      path: '/admin/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AuthenticatedAdminRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carteira/adicionar': {
      id: '/_authenticated/carteira/adicionar'
      path: '/adicionar'
      fullPath: '/carteira/adicionar'
      preLoaderRoute: typeof AuthenticatedCarteiraAdicionarRouteImport
      parentRoute: typeof AuthenticatedCarteiraRoute
    }
    '/_authenticated/carteira/saque': {
      id: '/_authenticated/carteira/saque'
      path: '/saque'
      fullPath: '/carteira/saque'
      preLoaderRoute: typeof AuthenticatedCarteiraSaqueRouteImport
      parentRoute: typeof AuthenticatedCarteiraRoute
    }
    '/_authenticated/admin/raspadinhas/': {
      id: '/_authenticated/admin/raspadinhas/'
      path: '/admin/raspadinhas'
      fullPath: '/admin/raspadinhas/'
      preLoaderRoute: typeof AuthenticatedAdminRaspadinhasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/raspadinhas/$id': {
      id: '/_authenticated/admin/raspadinhas/$id'
      path: '/admin/raspadinhas/$id'
      fullPath: '/admin/raspadinhas/$id'
      preLoaderRoute: typeof AuthenticatedAdminRaspadinhasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/raspadinhas/novo': {
      id: '/_authenticated/admin/raspadinhas/novo'
      path: '/admin/raspadinhas/novo'
      fullPath: '/admin/raspadinhas/novo'
      preLoaderRoute: typeof AuthenticatedAdminRaspadinhasNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedCarteiraRouteChildren {
  AuthenticatedCarteiraAdicionarRoute: typeof AuthenticatedCarteiraAdicionarRoute
  AuthenticatedCarteiraSaqueRoute: typeof AuthenticatedCarteiraSaqueRoute
}

const AuthenticatedCarteiraRouteChildren: AuthenticatedCarteiraRouteChildren = {
  AuthenticatedCarteiraAdicionarRoute: AuthenticatedCarteiraAdicionarRoute,
  AuthenticatedCarteiraSaqueRoute: AuthenticatedCarteiraSaqueRoute,
}

const AuthenticatedCarteiraRouteWithChildren =
  AuthenticatedCarteiraRoute._addFileChildren(
    AuthenticatedCarteiraRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCarteiraRoute: typeof AuthenticatedCarteiraRouteWithChildren
  AuthenticatedCuponsRoute: typeof AuthenticatedCuponsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIndicacaoRoute: typeof AuthenticatedIndicacaoRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedTransacoesRoute: typeof AuthenticatedTransacoesRoute
  AuthenticatedAdminBannersRoute: typeof AuthenticatedAdminBannersRoute
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminCuponsRoute: typeof AuthenticatedAdminCuponsRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminFinanceiroRoute: typeof AuthenticatedAdminFinanceiroRoute
  AuthenticatedAdminGanhadoresRoute: typeof AuthenticatedAdminGanhadoresRoute
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
  AuthenticatedAdminPremiosRoute: typeof AuthenticatedAdminPremiosRoute
  AuthenticatedAdminRelatoriosRoute: typeof AuthenticatedAdminRelatoriosRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminRaspadinhasIdRoute: typeof AuthenticatedAdminRaspadinhasIdRoute
  AuthenticatedAdminRaspadinhasNovoRoute: typeof AuthenticatedAdminRaspadinhasNovoRoute
  AuthenticatedAdminRaspadinhasIndexRoute: typeof AuthenticatedAdminRaspadinhasIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCarteiraRoute: AuthenticatedCarteiraRouteWithChildren,
  AuthenticatedCuponsRoute: AuthenticatedCuponsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIndicacaoRoute: AuthenticatedIndicacaoRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedTransacoesRoute: AuthenticatedTransacoesRoute,
  AuthenticatedAdminBannersRoute: AuthenticatedAdminBannersRoute,
  AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
  AuthenticatedAdminCuponsRoute: AuthenticatedAdminCuponsRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminFinanceiroRoute: AuthenticatedAdminFinanceiroRoute,
  AuthenticatedAdminGanhadoresRoute: AuthenticatedAdminGanhadoresRoute,
  AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
  AuthenticatedAdminPremiosRoute: AuthenticatedAdminPremiosRoute,
  AuthenticatedAdminRelatoriosRoute: AuthenticatedAdminRelatoriosRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminRaspadinhasIdRoute: AuthenticatedAdminRaspadinhasIdRoute,
  AuthenticatedAdminRaspadinhasNovoRoute:
    AuthenticatedAdminRaspadinhasNovoRoute,
  AuthenticatedAdminRaspadinhasIndexRoute:
    AuthenticatedAdminRaspadinhasIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CadastroRoute: CadastroRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ComoJogarRoute: ComoJogarRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  FaqRoute: FaqRoute,
  GanhadoresRoute: GanhadoresRoute,
  HomeRoute: HomeRoute,
  JogoResponsavelRoute: JogoResponsavelRoute,
  LoginRoute: LoginRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RaspadinhasRoute: RaspadinhasRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SuporteRoute: SuporteRoute,
  TermosRoute: TermosRoute,
  RaspadinhaSlugRoute: RaspadinhaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
